
version: "3"
services:
  nestjs-api:
    build:
      context: .
      target: development
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start:dev
    ports:
      - 3000:3000